import type {
  HugeCodeMissionLineage,
  HugeCodeRunSummary,
  HugeCodeTaskMode,
} from "@ku0/code-runtime-host-contract";
import { describe, expect, it } from "vitest";
import { projectCompletedRunToReviewPackSummary } from "./runtimeMissionControlReviewPackProjection";

function createLineage(): HugeCodeMissionLineage {
  return {
    objective: "Review delegated output",
    desiredEndState: [],
    hardBoundaries: [],
    doneDefinition: null,
    riskPolicy: null,
    taskMode: "delegate",
    executionProfileId: "profile-1",
    taskSource: null,
    threadId: "thread-1",
    requestId: "request-1",
    rootTaskId: null,
    parentTaskId: null,
    childTaskIds: [],
    reviewDecisionState: null,
    reviewDecisionSummary: null,
  };
}

function createRun(overrides: Partial<HugeCodeRunSummary> = {}): HugeCodeRunSummary {
  return {
    id: "run-1",
    taskId: "thread-1",
    workspaceId: "ws-1",
    taskSource: null,
    state: "review_ready",
    title: "Review delegated output",
    summary: "Review-ready result.",
    startedAt: 1,
    finishedAt: 2,
    updatedAt: 3,
    currentStepIndex: 0,
    pendingIntervention: null,
    executionProfile: {
      id: "profile-1",
      name: "Delegate",
      description: "Delegated execution.",
      executionMode: "remote_sandbox",
      autonomy: "autonomous_delegate",
      supervisionLabel: "Checkpointed autonomy",
      accessMode: "full-access",
      networkPolicy: "default",
      routingStrategy: "workspace_default",
      toolPosture: "workspace_extended",
      approvalSensitivity: "low_friction",
      identitySource: "workspace-routing",
      validationPresetId: "fast",
    },
    reviewProfileId: null,
    profileReadiness: null,
    routing: {
      backendId: "backend-primary",
      provider: "openai",
      providerLabel: "OpenAI",
      pool: "codex",
      routeLabel: "Workspace backend",
      routeHint: "Primary backend is ready.",
      health: "ready",
      enabledAccountCount: 1,
      readyAccountCount: 1,
      enabledPoolCount: 1,
    },
    approval: {
      status: "not_required",
      approvalId: null,
      label: "No pending approval",
      summary: "No approval gate is active.",
    },
    reviewDecision: null,
    intervention: null,
    operatorState: null,
    nextAction: {
      label: "Open review pack",
      action: "review",
      detail: "Inspect the evidence bundle.",
    },
    warnings: [],
    validations: [
      {
        id: "validation-1",
        label: "pnpm validate:fast",
        outcome: "passed",
        summary: "Fast validation passed.",
        startedAt: 1,
        finishedAt: 2,
      },
    ],
    artifacts: [],
    changedPaths: ["src/runtime.ts"],
    autoDrive: null,
    completionReason: "Completed successfully",
    reviewPackId: "review-pack:run-1",
    lineage: createLineage(),
    ledger: {
      traceId: "trace-1",
      checkpointId: null,
      recovered: false,
      stepCount: 1,
      completedStepCount: 1,
      warningCount: 0,
      validationCount: 1,
      artifactCount: 0,
      evidenceState: "confirmed",
      backendId: "backend-primary",
      routeLabel: "Workspace backend",
      completionReason: "Completed successfully",
      lastProgressAt: 3,
    },
    checkpoint: null,
    missionLinkage: null,
    actionability: null,
    reviewGate: null,
    reviewFindings: [],
    reviewRunId: null,
    skillUsage: [],
    autofixCandidate: null,
    sessionBoundary: null,
    continuation: {
      state: "ready",
      pathKind: "review",
      source: "review_actionability",
      summary: "Canonical continuation is ready.",
      detail: "Open the published continuation path.",
      recommendedAction: "Use the canonical continuation path.",
      reviewPackId: "review-pack:run-1",
      target: null,
      reviewActionability: null,
      sessionBoundary: {
        workspaceId: "ws-1",
        taskId: "thread-1",
        runId: "run-1",
        missionTaskId: "thread-1",
        sessionKind: "thread",
        threadId: "thread-1",
        requestId: "request-1",
        reviewPackId: "review-pack:run-1",
        checkpointId: null,
        traceId: "trace-1",
        navigationTarget: {
          kind: "thread",
          workspaceId: "ws-1",
          threadId: "thread-1",
        },
      },
    },
    nextOperatorAction: null,
    governance: {
      state: "action_required",
      label: "Action required",
      summary: "Governance evidence recorded.",
      blocking: false,
      suggestedAction: "review_result",
      availableActions: ["review_result"],
    },
    placement: {
      summary: "Workspace-default backend confirmed.",
      lifecycleState: "confirmed",
      resolutionSource: "workspace_default",
      requestedBackendIds: ["backend-primary"],
      resolvedBackendId: "backend-primary",
      readiness: "ready",
      healthSummary: "placement_ready",
      attentionReasons: [],
      rationale: "Primary backend remained healthy.",
    },
    operatorSnapshot: null,
    workspaceEvidence: {
      summary: "Workspace evidence for run-1",
      buckets: [],
    },
    missionBrief: null,
    relaunchContext: null,
    subAgents: [],
    publishHandoff: null,
    takeoverBundle: null,
    executionGraph: null,
    selectedOpportunityId: null,
    wakeReason: null,
    wakeState: null,
    sourceCitations: null,
    queuePosition: null,
    nextEligibleAction: null,
    ...overrides,
  };
}

describe("runtimeMissionControlReviewPackProjection", () => {
  it("projects terminal runs into review-pack summaries using canonical continuation truth", () => {
    const reviewPack = projectCompletedRunToReviewPackSummary(createRun(), {
      deriveTaskMode: (): { mode: HugeCodeTaskMode | null } => ({
        mode: "delegate",
      }),
      deriveValidationOutcome: () => "passed",
      buildMissionLineage: () => createLineage(),
      buildRunWorkspaceEvidence: ({ run }) => run.workspaceEvidence,
      buildGovernanceSummary: () => ({
        state: "action_required",
        label: "Action required",
        summary: "Governance evidence recorded.",
        blocking: false,
        suggestedAction: "review_result",
        availableActions: ["review_result"],
      }),
      buildRuntimeContinuationDescriptor: () => ({
        state: "ready",
        summary: "Canonical continuation is ready.",
        detail: "Open the published continuation path.",
        recommendedAction: "Use the canonical continuation path.",
        continuePathLabel: "Continue from runtime checkpoint",
        truthSourceLabel: "Runtime continuation",
        continuityOverview: "Checkpoint and review handoff are aligned.",
        checkpointDurabilityState: "durable",
        hasHandoffPath: true,
        canSafelyContinue: true,
        reviewFollowUpActionable: true,
      }),
      buildReviewPackAssumptions: () => ["Assume runtime evidence is current."],
      buildReviewPackBackendAudit: () => ({
        summary: "Backend primary remained healthy.",
        details: ["backend-primary"],
        missingReason: null,
      }),
      buildReviewPackEvidenceRefs: () => ({
        traceId: "trace-1",
        checkpointId: null,
        diffArtifactIds: [],
        validationArtifactIds: [],
        logArtifactIds: [],
        commandArtifactIds: [],
      }),
      buildReviewPackFileChanges: () => ({
        paths: ["src/runtime.ts"],
        totalCount: 1,
        summary: "1 file changed",
        missingReason: null,
      }),
      buildReviewPackReproductionGuidance: () => ["Run pnpm validate:fast."],
      buildReviewPackRollbackGuidance: () => ["Revert src/runtime.ts if needed."],
      isTerminalRunState: (state) => state === "review_ready",
    });

    expect(reviewPack).toMatchObject({
      id: "review-pack:run-1",
      runId: "run-1",
      reviewStatus: "ready",
      validationOutcome: "passed",
      recommendedNextAction: "Open the published continuation path.",
      continuation: {
        summary: "Canonical continuation is ready.",
      },
      reviewDecision: {
        status: "pending",
        reviewPackId: "review-pack:run-1",
      },
    });
  });

  it("returns null for non-terminal runs", () => {
    expect(
      projectCompletedRunToReviewPackSummary(
        createRun({
          state: "running",
          reviewPackId: null,
        }),
        {
          deriveTaskMode: (): { mode: HugeCodeTaskMode | null } => ({ mode: "delegate" }),
          deriveValidationOutcome: () => "passed",
          buildMissionLineage: () => createLineage(),
          buildRunWorkspaceEvidence: ({ run }) => run.workspaceEvidence,
          buildGovernanceSummary: () => null,
          buildRuntimeContinuationDescriptor: () => ({
            state: "missing",
            summary: "Missing continuation",
            detail: null,
            recommendedAction: null,
            continuePathLabel: null,
            truthSourceLabel: null,
            continuityOverview: null,
            checkpointDurabilityState: "missing",
            hasHandoffPath: false,
            canSafelyContinue: false,
            reviewFollowUpActionable: false,
          }),
          buildReviewPackAssumptions: () => [],
          buildReviewPackBackendAudit: () => ({
            summary: "Backend primary remained healthy.",
            details: [],
            missingReason: null,
          }),
          buildReviewPackEvidenceRefs: () => ({
            traceId: null,
            checkpointId: null,
            diffArtifactIds: [],
            validationArtifactIds: [],
            logArtifactIds: [],
            commandArtifactIds: [],
          }),
          buildReviewPackFileChanges: () => ({
            paths: [],
            totalCount: 0,
            summary: "No changed files recorded.",
            missingReason: null,
          }),
          buildReviewPackReproductionGuidance: () => [],
          buildReviewPackRollbackGuidance: () => [],
          isTerminalRunState: () => false,
        }
      )
    ).toBeNull();
  });
});
