export {
  fetchGit,
  getGitCommitDiff,
  getGitHubIssueDetails,
  getGitHubIssues,
  getGitHubPullRequestComments,
  getGitHubPullRequestDiff,
  getGitHubPullRequests,
  getGitRemote,
  listGitRoots,
  pullGit,
  pushGit,
  revertGitAll,
  syncGit,
} from "./desktopHostGit";
